---
config:
  layout: elk
---
flowchart LR
    Mandate("Mandate") -- hasRelatedInitiative --> Ini("Initiative")
    Mandate -- hasRelatedRequest --> Req("Request")
    Req -- isRequestType --> reqtype("Request Type")
    Mandate -- hasRelatedIntervention --> Interv("Intervention")
    Interv --> hasPublicationType("Publication Type")
    Mandate -- didParliamentaryActivity --> PAct("Parliamentary Activity")
    Mandate -- wasRapporteurIn --> Ini & Pet("Petition") & PE("Public Expenses") & EUINI("European Initiatives")
    PE -- isActivityType --> ActType("Activity Type")
    Mandate -- hasOpinion --> Opi("Parliamentary Opinion")
    Mandate -- hasRelatedEvent --> Event("Event")
    Mandate -- hasVisit --> Visit("Visit")
    Mandate -- hasMeetings --> Meet("Meeting")
    Mandate -- hasHearing --> Hear("Hearing")
    Mandate -- didYouthParliamentActivity --> YPA("Youth Parliament Activity")
    YPA -- tookPlaceIn --> TeaEs("Teaching Establishment")
    TeaEs -- isType --> EsType("Establishment Type")
    Mandate -- hasMembership --> Mem("Membership")
    Mem -- relatedEventualDelegation --> DelE("Eventual Delegation")
    Mem -- relatedPermanentDelegation --> DelP("Permanent Delegation")
    Mem -- relatedFriendshipParliamentaryGroup --> FPG("Friendship Parliamentary Group")
    Mem -- inParliamentaryGroup --> PG
    DelP -- hasMeeting --> DelPM("Permanent Delegation Meeting")
    LS("Legislative Session") -- hasLegislature --> Leg("Legislature")
    PG("Parliamentary Group") -- hasParty --> Party("Party")
    PG -- hasLegislature --> Leg
    MP("Member of Parliament") -.-> Person("Person")
    MG("Member of Government") -.-> Person
    Guest("Guest") -.-> Person
    Mandate -- hasLegislature --> Leg
    Mandate -- hasDuty --> Duty("Duty")
    Mandate -- hasSituation --> Situation("Situation")
    Ini -- hasAuthor --> MP
    Ini -- hasLegislature --> Leg
    Ini -- hasLegislativeSession --> LS
    Ini -- hasAnnex --> An("Annex")
    Ini -- hasChangeProposal --> CP("Change Proposal")
    CP -- hasAuthor --> MP
    DAR("DAR Publication") -- hasLegislature --> Leg
    DAR -- hasLegislativeSession --> LS
    CP -- hasPublication --> DAR
    Ini -- hasProponent --> MP & CG("Citizen Group") & Com("Commission") & Gov("Government") & RLA("Regional Legislative Assembly") & PG
    Ini -- originatedFromEU --> EU("European Initiative")
    Ini -- originatedFrom --> Ini
    Ini -- originated --> Ini
    Ini -- hasContent --> Content("Content")
    Ini -- hasPetition --> P("Petition")
    P -- hasLegislature --> Leg
    P -- hasLegislativeSession --> LS
    IT("InitiativeType") -.-> Ini
    Ini -- hasEvent --> Ev("Event")
    Ev -- hasJointInitiatives --> Ini
    Ev -- hasAnnex --> An
    Ev -- hasPublication --> DAR
    Ev -- hasAppeal --> MP & PG
    Ev -- hasJointActivity --> Act("Activitiy")
    Ev -- hasJointDiscussion --> P & PAP("Public Account Proceedings")
    Ev -- hasApprovedDiploma --> D("Diploma")
    Ev -- hasVote --> V("Vote")
    V -- hasAbsent --> MP & PG
    V -- hasInFavor --> MP & PG
    V -- hasAgainst --> MP & PG
    V -- hasAbstained --> MP & PG
    Ev -- hasIntervention --> I("Intervention")
    I -- hasSpeaker --> Sps("Speakers")
    Sps -- hasSpeaker --> MP & MG
    Sps -- hasGuest --> Guest
    EC("Event Commission") -- hasCommission --> C("Commission")
    EC -- hasSubCommission --> C
    Ev -- hasEventCommission --> EC
    EC -- hasVote --> V
    C -- hasPublication --> DAR
    C -- hasLegislature --> Leg
    EC -- hasLegislature --> Leg
    EC -- hasLegislativeSession --> LS
    EC -- hasPublication --> DAR
    R("Rapporteur") -- hasMemberOfParliament --> MP
    EC -- hasRapporteur --> R
    EC -- hasRemittance --> Rem("Remittances")
    EC -- hasDocument --> Doc("Document")
    EC -- hasReportPublication --> RP("Report Publication")
    EC -- hasHearing --> RA("Related Activity")
    EC -- hasAudience --> RA
    MP -- hasEducation --> Edu("Habilitations")
    MP -- hasAward --> Award("Decoration")
    MP -- hasTitle --> Title("Title")
    MP -- hasPublished --> Work("Published Work")
    MP -- servedMandate --> Mandate
    Mem -- in --> Body("Organizational Body")