---
config:
  layout: elk
---
flowchart LR
    Person("MP") -- hasHabilitation --> Edu("Habilitation")
    Person -- hasAward --> Award("Award")
    Person -- hasTitle --> Title("Title")
    Person -- hasPublished --> Work("Published Work")
    Person -- servedMandate --> Mandate("Mandate")
    Person -- performedRole --> Role("Role")
    Mandate -- hasMembership --> Mem("Membership")
    Mem -- in --> Body("OrganisationalBody")