---
config:
  layout: elk
---
flowchart LR
    Person("MP") -- hasHabilitation --> Edu("Habilitation")
    Person -- hasAward --> Award("Award")
    Person -- hasTitle --> Title("Title")
    Person -- hasPublished --> Work("Published Work")
    Person -- performedRole --> Role("Role")