---
config:
  layout: elk
---
flowchart LR
   
    Ini(Initiative) -- belongsToLegislature --> Leg(Legislature)
    Ini -- belongsToLegislativeSession --> LS(LegislativeSession)
    Ini -- hasAuthor --> MP
    Ini -- hasProponent --> MP & CG(CitizenGroup) & Com(Commission) & Gov(Government) & RLA(RegionalLegislativeAssembly) & PG(PG)
    Ini -- hasAnnex --> Document(Document)
    Ini -- hasEvent -->Event
    Ini -- grewOutOf --> EU(EuropeanInitiative) & Ini
    Ini -- ledTo --> Ini
    Ini -- receivedChangeProposal --> CP(ChangeProposal)
    Ini -- hasRelatedPetition --> P(Petition)
    Ini -- hasContent --> Document

    ConstitutionalRevisionProject("ConstitutionalRevisionProject") -.->Ini
    DeliberationProject("DeliberationProject") -.->Ini
    LawProject("LawProject") -.->Ini
    LawProposal("LawProposal") -.->Ini
    ParliamentaryAppreciation("ParliamentaryAppreciation") -.->Ini
    ParliamentaryInquiry("ParliamentaryInquiry") -.->Ini
    PopularReferendumInitiative("PopularReferendumInitiative") -.->Ini
    Ratification("Ratification") -.->Ini
    ResolutionProposal("ResolutionProposal") -.->Ini
    ResolutionProject("ResolutionProject") -.->Ini
    RulesOfProcedureProject("RulesOfProcedureProject") -.->Ini

    CP(ChangeProposal) -- isProposedBy --> MP(MemberOfParliament)
    CP -- isPublishedIn --> DAR(DARPublication)
    CP -- isProposedBy --> PG

    %%DAR -.-> PUB("Publication")
    %%RP("ReportPublication") -.-> PUB
    DAR -- belongsToLegislature --> Leg
    DAR -- belongsToLegislativeSession --> LS
    
    DARSeries1("DARSeries1") -.-> DAR
    DARSeries2("DARSeries2") -.-> DAR
    DARSeparata("DARSeparata") -.-> DAR
    DARSeries2A("DARSeries2A") -.-> DAR
    DARSeries2B("DARSeries2B") -.-> DAR
    DARSeries2C("DARSeries2C") -.-> DAR
    DARSeries2D("DARSeries2D") -.-> DAR
    DARSeries2E("DARSeries2E") -.-> DAR
    DARSeries1A("DARSeries1A") -.-> DAR
    DARSeries2CRC("DARSeries2CRC") -.-> DAR
    DARSeries2CGOPOE("DARSeries2CGOPOE") -.-> DAR
    DARSeries2SCOE("DARSeries2SCOE") -.-> DAR
    DARSeries2CCEI("DARSeries2CCEI") -.-> DAR
    DARSeries2SOE("DARSeries2SOE") -.-> DAR
    
    P(Petition) -- belongsToLegislature --> Leg
    P -- belongsToLegislativeSession --> LS

    RLA -- location --> Place(Place)

    LDocument(LegislativeDocument) -.-> Document

    CitizenGroup(CitizenGroup)

    E(Event) -- approvesDiploma --> LDocument
    E -- hasDiscussion --> Discussion
    E -- happensJointlyWithInitiative --> Ini
    E -- discussedJointlyWith --> P
    E -- hasAnnex --> Document
    E -- hasVote --> Vote(Vote)
    E -- receivedAppeal --> MP & PG
    E -- hasActivity --> Acttivity(Activity)
    E -- isPublishedIn --> DAR

    Vote -- hasVoteAgainstFrom --> MP & PG
    Vote -- hasVoteInFavourFrom --> MP & PG
    Vote -- hasAbstensionFrom --> MP & PG
    Vote -- isAbsentee --> MP
    Vote -- isPublishedinDAR --> DAR

    Discussion -- hasIntervention --> Intervention(Intervention)

    Intervention -- isPublishedInDAR --> DAR
    Intervention -- hasSpeaker --> Person(Person)

    CE(CommissionEvent) -- attributedToCommission --> Com
    CE -- hasAudition --> Audition(Audition)
    CE -- hasHearing --> Hearing(Hearing)
    CE -- isPubilshedInDAR --> DAR
    CE -- hasVote --> Vote
    CE -- hasTransmission --> Transmission("Transmission")
    CE -- hasRapporteur --> MP
    CE -- hasPublishedReport --> DAR
    CE -- createsDocument --> Document
    CE -- hasSubCommission --> Com
