---
config:
  layout: elk
---
flowchart LR
    MP("MP")
    Req("Requisition")
    ReqReq("Request")
    Inq("Inquiry")
    Interv("Intervention")
    PAct("Parliamentary Activity")
    PE("Public Accounts")
    Event("Event")
    Visit("Visit")
    Audition("Audition")
    Group("Group")
    Hearing("Hearing")
    YPA("Youth Parliament Activity")
    TeaEs("Teaching Establishment")
    EsType("Establishment Type")
    Mem("Membership")
    Del("Delegation")
    DelE("Temporary Delegation")
    DelP("Permanent Delegation")
    FPG("Friendship Parliamentary Group")
    DelPM("Permanent Delegation Meeting")
    ComA("Comission Activity")

    MP -- didCommissionActivity --> ComA
    ComA -.-> Hearing
    ComA -.-> Audition
    ComA -.-> Event
    ComA -.-> Visit
    MP -- didRequest --> Req
    Req -.-> ReqReq
    Req -.-> Inq
    MP -- didIntervention --> Interv
    MP -- didParliamentaryActivity --> PAct
    MP -- wasRapporteurIn --> PE
    PE -- isActivityType --> ActType
    MP -- didYouthParliamentActivity --> YPA
    YPA -- tookPlaceIn --> TeaEs
    TeaEs -- isType --> EsType
    MP -- hasMembership --> Mem
    DelP -- didDelegationMeeting --> DelPM
    Mem -- inGroup --> Group 
    Group -.-> FPG
    Group -.-> Del
    Del -.-> DelE
    Del -.-> DelP