---
config:
  layout: elk
---
flowchart LR
    Mandate("Mandate")
    Ini("Initiative")
    Req("Request")
    reqtype("Request Type")
    Interv("Intervention")
    PubType("Publication Type")
    PAct("Parliamentary Activity")
    Pet("Petition")
    PE("Public Accounts")
    EUINI("European Initiatives")
    Event("Event")
    Visit("Visit")
    Meet("Meeting")
    Hear("Hearing")
    YPA("Youth Parliament Activity")
    TeaEs("Teaching Establishment")
    EsType("Establishment Type")
    Mem("Membership")
    DelE("Temporary Delegation")
    DelP("Permanent Delegation")
    FPG("Friendship Parliamentary Group")
    DelPM("Permanent Delegation Meeting")

    Mandate -- hasRelatedInitiative --> Ini
    Mandate -- hasRelatedRequest --> Req
    Req -- isRequestType --> reqtype
    Mandate -- hasRelatedIntervention --> Interv
    Interv -- hasPublicationType  --> PubType
    Mandate -- didParliamentaryActivity --> PAct
    Mandate -- wasRapporteurIn --> Ini & Pet & PE & EUINI
    PE -- isActivityType --> ActType
    Mandate -- hasRelatedEvent --> Event
    Mandate -- hasVisit --> Visit
    Mandate -- hasMeetings --> Meet
    Mandate -- hasHearing --> Hear
    Mandate -- didYouthParliamentActivity --> YPA
    YPA -- tookPlaceIn --> TeaEs
    TeaEs -- isType --> EsType
    Mandate -- hasMembership --> Mem
    Mem -- relatedTemporaryDelegation --> DelE
    Mem -- relatedPermanentDelegation --> DelP
    Mem -- relatedFriendshipParliamentaryGroup --> FPG
    DelP -- hasMeeting --> DelPM