---
config:
  layout: elk
---
flowchart TB
    LS("LegislativeSession") -- belongsToLegislature --> Leg("Legislature")
    PG("PG") -- isOfParty --> Party("Party")
    PG -- belongsToLegislature --> Leg
    MP("MP") -.-> Person("Person")
    MG("MG") -.-> Person
    Guest("Guest") -.-> Person
    MP -- servedMandate --> Mandate("Mandate")
    Mandate -- belongsToLegislature --> Leg
    Mandate -- hasMembership --> M(Membership)
    M -- isMemberOf --> PG & OB("OrganisationalBody")
    Duty(Duty)
    Situation(Situation)
    Mandate -- hasDuty --> Duty
    Mandate -- hasSituation --> Situation
