---
config:
  layout: elk
---
flowchart TB
    LS["LegislativeSession"] -- belongsToLegislature --> Leg["Legislature"]
    PG -- isOfParty --> Party
    PG -- belongsToLegislature --> Leg

    MP["MemberOfParliament"] -.-> Person
    MP -- servedMandate --> Mandate
    MP -- participatedLegislature --> Leg
    MP -- didRequisition --> Requisition
    MP -- didYouthParliamentActivity --> YouthParliamentActivity
    MP -- hasMembership --> M["Membership"]
    MP -- didCommissionActivity --> CommissionActivity
    MP -- didParliamentaryActivity --> ParliamentaryActivity
    MP -- wasRapporteurIn --> PublicAccount & EuropeanInitiative


    M -- isMemberOf --> PG
    M -- isMemberOf --> OB["OrganisationalBody"]
    M -- isMemberOf --> Group
    M -- hasRole --> Role

    OB -- belongsTo --> Leg

    C[Commission] -.-> OB
    WG["WorkingGroup"] -.-> OB
    AR-WG["ARWorkingGroup"] -.-> OB

    MG["MemberOfGovernment"] -.-> Person
    MG -- holdsDuty --> Post
    MG -- belongsToGovernmet --> G[Government]
    
  
    Guest -.-> Person
    Guest --holdsDuty --> Post


    PAR -.-> Post
    VicePAR -.-> Post
    Secretary -.-> Post
    ViceSecretary -.-> Post
   
    Mandate -- belongsToLegislature --> Leg
    Mandate -- hasMembership --> M
    Mandate -- isInSituation --> SituationHolding
    Mandate -- holdsDuty -->DutyHolding
    Mandate -- inConstituency --> Constituency
   
    C -- isPublishedIn --> DP[DARPublication]
    C -- isSubCommissionOf --> C
    C -- hasSubCommission --> C

    Withdrawal -.-> Situation
    Incumbent -.-> Situation
    PermantentIncumbent -.-> Situation
    TemporaryIncumbent -.-> Situation
    Deceased -.-> Situation
    Disqualified -.-> Situation
    LossOfMandate -.-> Situation
    Resigned -.-> Situation
    Alternate -.-> Situation
    Suspended -.-> Situation
